### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by harimaruthachalam** [rawatamit/GraphMatching#1]
Hi Rawat,

I am Hari from IITM. I have a query regarding the compilation. I am getting the following error while `make`, c++: error: unrecognized command line option ‘-std=c++14’. 

g++ --version
g++-5 (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010

c++ --version
c++ (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5

**Comment by rawatamit** [comment]
Hi Hari,

The g++ version on your system is very old.
I would suggest updating it to any version >= 6, that should fix it.

- Amit

**Comment by harimaruthachalam** [comment]
Hi,

Thanks for the quick response. I have installed g++ -6

g++-6 (Ubuntu 6.4.0-17ubuntu1~14.04) 6.4.0 20180424

The problem still exists.

**Comment by rawatamit** [comment]
Can you try removing the problematic flags from the build? They are in the CMakeLists.txt inside the root folder.

**Comment by harimaruthachalam** [comment]
Commenting out -std=c++14 throws bunch of errors

[1/17] Building CXX object lib/CMakeFiles/graph.dir/MatchingAlgorithm.cc.o
[2/17] Building CXX object lib/CMakeFiles/graph.dir/StableMarriage.cc.o
FAILED: /usr/bin/c++    -I../include -I../lib/include -MMD -MT lib/CMakeFiles/graph.dir/MatchingAlgorithm.cc.o -MF "lib/CMakeFiles/graph.dir/MatchingAlgorithm.cc.o.d" -o lib/CMakeFiles/graph.dir/MatchingAlgorithm.cc.o -c ../lib/MatchingAlgorithm.cc
In file included from ../include/BipartiteGraph.h:7:0,
                 from ../include/MatchingAlgorithm.h:4,
                 from ../lib/MatchingAlgorithm.cc:1:
../include/TDefs.h:19:9: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
 typedef std::shared_ptr<Vertex> VertexPtr;
         ^
../include/TDefs.h:22:18: error: ‘shared_ptr’ is not a member of ‘std’
 typedef std::map<std::shared_ptr<Vertex>, PartnerList> MatchedPairListType;
                  ^
../include/TDefs.h:22:18: error: ‘shared_ptr’ is not a member of ‘std’
../include/TDefs.h:22:40: error: wrong number of template arguments (1, should be 4)
 typedef std::map<std::shared_ptr<Vertex>, PartnerList> MatchedPairListType;
                                        ^
In file included from /usr/include/c++/4.8/map:61:0,
                 from ../include/BipartiteGraph.h:4,
                 from ../include/MatchingAlgorithm.h:4,
                 from ../lib/MatchingAlgorithm.cc:1:
/usr/include/c++/4.8/bits/stl_map.h:96:11: error: provided for ‘template<class _Key, class _Tp, class _Compare, class _Alloc> class std::map’
     class map
           ^
In file included from ../include/BipartiteGraph.h:7:0,
                 from ../include/MatchingAlgorithm.h:4,
                 from ../lib/MatchingAlgorithm.cc:1:
../include/TDefs.h:22:41: error: expected unqualified-id before ‘,’ token
 typedef std::map<std::shared_ptr<Vertex>, PartnerList> MatchedPairListType;
                                         ^
../include/TDefs.h:22:54: error: expected initializer before ‘>’ token
 typedef std::map<std::shared_ptr<Vertex>, PartnerList> MatchedPairListType;

Sharing first 30 lines of error messages from 800 lines of error messages.

**Comment by rawatamit** [comment]
Is there a way you could install gcc 8.2.1 to your system and add the c++14 flag? I have it installed and it works fine for me. I'm sure this is because of an old compiler version.

**Comment by harimaruthachalam** [comment]
Regarding updating gcc and g++, I followed the instructions provided @ http://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu

Now, the compilation is successful and I can run the program without any trouble.

Thanks for your support @rawatamit  and I am closing the thread
